/**
 * Auto-generated by scripts/generate_web_bot_auth_keys.mjs — DO NOT EDIT.
 *
 * The Ed25519 keypair backing /.well-known/http-message-signatures-directory.
 * The private JWK below is the site's Web Bot Auth signing identity and is
 * treated as a public bot key (comparable to a TLS certificate public/private
 * pair). To rotate, run `node scripts/generate_web_bot_auth_keys.mjs` and
 * commit the updated file.
 */

export const WEB_BOT_AUTH_PUBLIC_JWK = {
  "crv": "Ed25519",
  "x": "j1RResRnGlZcJQrVs1lAUzhxm4qwWXc0wgmErRVz2v8",
  "kty": "OKP",
  "alg": "EdDSA",
  "use": "sig",
  "kid": "xkvK7C_5SG0IfYM3obc3RMtISCiuD_EX1NSN0apY1Hs"
} as const;

export const WEB_BOT_AUTH_PRIVATE_JWK = {
  "crv": "Ed25519",
  "d": "3fL20Nft5XA7qL6wl0RM-nzoIivvoAIzzQtvVDZdVLE",
  "x": "j1RResRnGlZcJQrVs1lAUzhxm4qwWXc0wgmErRVz2v8",
  "kty": "OKP",
  "alg": "EdDSA",
  "use": "sig",
  "kid": "xkvK7C_5SG0IfYM3obc3RMtISCiuD_EX1NSN0apY1Hs"
} as const;

export const WEB_BOT_AUTH_JWKS = {
  keys: [WEB_BOT_AUTH_PUBLIC_JWK],
} as const;
