/**
 * generate_web_bot_auth_keys.mjs
 *
 * Generates the Ed25519 keypair that backs the Web Bot Auth signing
 * directory at /.well-known/http-message-signatures-directory.
 *
 * The directory is signed with this key on every response from
 * `functions/.well-known/http-message-signatures-directory.ts`, and the
 * SPA's outbound Web Bot Auth fetches are signed with the same private
 * key material.
 *
 * Why a build-time script:
 *   - We want a stable `kid` (JWK thumbprint) embedded in the JWKS.
 *   - We want the JWKS body served at /.well-known/http-message-signatures-directory
 *     to be a *static* file so crawlers can cache it.
 *   - We want a reproducible artifact committed to the repo so the
 *     Cloudflare Pages Function can read it at request time without any
 *     external secret store.
 *
 * Threat model: this private key is a *bot identity*, not a user secret.
 * It is published next to the public JWKS so receiving sites can verify
 * the bot's signed requests. The Cloudflare Pages Functions runtime
 * needs access to it; committing it to the repo (alongside the public
 * JWKS that proves possession) is the simplest deployment path and
 * matches the Web Bot Auth reference architecture. To rotate the key,
 * re-run this script and commit the new pair — the `kid` in the JWKS
 * changes, which signals key rotation to verifiers.
 *
 * Usage:
 *   node scripts/generate_web_bot_auth_keys.mjs            # generate a new keypair
 *   node scripts/generate_web_bot_auth_keys.mjs --check   # only verify the existing keypair is well-formed
 *
 * Files written:
 *   .web-bot-auth/public.jwk.json   — public JWK (also embedded in the JWKS directory)
 *   .web-bot-auth/private.jwk.json  — private JWK (read at runtime by the Pages Function)
 */

import { generateKeyPair, exportJWK, calculateJwkThumbprint } from 'jose';
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const outDir = resolve(repoRoot, '.web-bot-auth');
const publicPath = resolve(outDir, 'public.jwk.json');
const privatePath = resolve(outDir, 'private.jwk.json');
const inlinePath = resolve(repoRoot, 'functions/.well-known/_web-bot-auth-keys.ts');

function emitInlineModule(publicJwk, privateJwk) {
  // The function source is committed and bundled by Cloudflare Pages,
  // so the private JWK must be embedded as a module-level constant
  // (the function cannot read from the filesystem at request time).
  const body =
`/**
 * Auto-generated by scripts/generate_web_bot_auth_keys.mjs — DO NOT EDIT.
 *
 * The Ed25519 keypair backing /.well-known/http-message-signatures-directory.
 * The private JWK below is the site's Web Bot Auth signing identity and is
 * treated as a public bot key (comparable to a TLS certificate public/private
 * pair). To rotate, run \`node scripts/generate_web_bot_auth_keys.mjs\` and
 * commit the updated file.
 */

export const WEB_BOT_AUTH_PUBLIC_JWK = ${JSON.stringify(publicJwk, null, 2)} as const;

export const WEB_BOT_AUTH_PRIVATE_JWK = ${JSON.stringify(privateJwk, null, 2)} as const;

export const WEB_BOT_AUTH_JWKS = {
  keys: [WEB_BOT_AUTH_PUBLIC_JWK],
} as const;
`;
  mkdirSync(dirname(inlinePath), { recursive: true });
  writeFileSync(inlinePath, body, 'utf8');
}

async function generate() {
  mkdirSync(outDir, { recursive: true });
  const { publicKey, privateKey } = await generateKeyPair('EdDSA', { crv: 'Ed25519', extractable: true });
  const publicJwk = await exportJWK(publicKey);
  const privateJwk = await exportJWK(privateKey);
  publicJwk.alg = 'EdDSA';
  publicJwk.use = 'sig';
  publicJwk.kid = await calculateJwkThumbprint(publicJwk, 'sha256');
  privateJwk.alg = 'EdDSA';
  privateJwk.use = 'sig';
  privateJwk.kid = publicJwk.kid;
  writeFileSync(publicPath, `${JSON.stringify(publicJwk, null, 2)}\n`, 'utf8');
  writeFileSync(privatePath, `${JSON.stringify(privateJwk, null, 2)}\n`, 'utf8');
  emitInlineModule(publicJwk, privateJwk);
  console.log(`Generated new Ed25519 keypair:`);
  console.log(`  kid:      ${publicJwk.kid}`);
  console.log(`  public:   ${publicPath}`);
  console.log(`  priv:     ${privatePath}`);
  console.log(`  inline:   ${inlinePath}`);
}

async function check() {
  if (!existsSync(publicPath) || !existsSync(privatePath)) {
    console.error(`Missing key files. Run without --check to generate.`);
    process.exit(1);
  }
  const publicJwk = JSON.parse(readFileSync(publicPath, 'utf8'));
  const privateJwk = JSON.parse(readFileSync(privatePath, 'utf8'));
  if (!publicJwk.kid || !privateJwk.kid || publicJwk.kid !== privateJwk.kid) {
    console.error(`kid mismatch between public and private JWKs.`);
    process.exit(1);
  }
  if (publicJwk.crv !== 'Ed25519' || publicJwk.kty !== 'OKP') {
    console.error(`Public JWK is not an OKP Ed25519 key.`);
    process.exit(1);
  }
  console.log(`Existing key OK (kid=${publicJwk.kid}).`);
}

const mode = process.argv.includes('--check') ? 'check' : 'generate';
if (mode === 'check') {
  await check();
} else {
  await generate();
}
